- src/Block.ts
- src/FilterManager.ts
- src/app.ts
- src/style.scss
Please have a look. 
Issue #25 
Current State:
> Density plot updated

- src/ConnectionLines.ts
- src/FilterManager.ts
- src/RangeManager.ts
- src/app.ts
I am not sure If this has to be merged or not. But to delete this branch, we can keep the current state of the connection line. 
In the previous version, the thickness was not maintained and not clickable. But still, current version lacks full functionality.
See Issue #18
> Connection line with Thickness

- data/index.json
- src/SupportView.ts
- src/app2.ts
- src/column/AColumn.ts
- src/column/AVectorColumn.ts
- src/column/CategoricalColumn.ts
- src/column/ColumnManager.ts
- src/column/MatrixColumn.ts
- src/filter/AFilter.ts
- src/filter/CategoricalFilter.ts
- src/filter/FilterManager.ts
- src/filter/MatrixFilter.ts
- src/filter/NumberFilter.ts
- src/filter/StringFilter.ts
- src/styles/_app2.scss
- src/styles/_filterManager.scss
@katush @mijar 
Please have a look and test in your machine and let me know if there are some bugs.
> Feature filter dialog

- src/column/AColumn.ts
- src/style.scss
issue #38 addressed
@bikramkawan @katush ?
> Showing toolbar on header hover

- src/column/AColumn.ts
- src/column/AVectorColumn.ts
- src/column/ColumnManager.ts
- src/column/MatrixColumn.ts
- src/column/utils.ts
don't forget to update your dependencies (phovea_core, phovea_vis)
> Column relayout

- src/column/AColumn.ts
- src/style.scss
#69 addressed, ready for integration of sorting functionality that Bikram previously created...
@bikramkawan
> Sorting button 69

- src/column/AColumn.ts
- src/column/CategoricalColumn.ts
- src/column/ColumnManager.ts
- src/column/MatrixColumn.ts
- src/column/NumberColumn.ts
- src/column/StringColumn.ts
- src/style.scss
- src/styles/_app.scss
- src/styles/_app2.scss
- src/styles/_vars.scss
I am going to continue working on this to enhance the behavior, but it is at least working a little bit now...
I will create issues related to the actual individual steps for the column manager and I want to continue with the development respectively to each of these (not yet but soon existing) issues.:-)
> Basic column management behavior

- src/app2.ts
- src/column/AColumn.ts
- src/column/AVectorColumn.ts
- src/column/ColumnManager.ts
- src/column/MatrixColumn.ts
- src/filter/CategoricalFilter.ts
@mijar @katush 
Please review it.
> Added  View snapshot for each data on filter operation.

- src/app2.ts
- src/column/AColumn.ts
- src/column/AVectorColumn.ts
- src/column/ColumnManager.ts
- src/column/MatrixColumn.ts
- src/column/SortColumn.ts
- src/filter/FilterManager.ts
Please test on your machine once.
@katush @mijar
> Feature #3

- src/app2.ts
- src/column/ColumnManager.ts
- src/column/MatrixColumn.ts
> updated matrix filter method #91

- src/column/SortColumn.ts
> Sorting for categorical is based on alphabetical

- src/column/MatrixColumn.ts
@mijar @katush I updated matrix after we filter from other id type. Please check in your side.
> Adapt matrix relayout #98

- src/column/AColumn.ts
- src/column/AVectorColumn.ts
- src/column/ColumnManager.ts
@mijar @katush I have moved the logic of sort from AColumn to AVector.
> Moved the logic of sort into AVector Colum #101

- src/app2.ts
- src/column/ColumnManager.ts
- src/column/MatrixColumn.ts
- src/styles/_filterManager.scss
@mijar @katush Please check on your side.
> preview of data lost #94

- src/SortManager.ts
- src/app2.ts
- src/column/AColumn.ts
- src/column/AVectorColumn.ts
- src/column/ColumnManager.ts
- src/column/SortColumn.ts
Single sorting is the first step for hierarchical sorting.
@katush @mijar
> single sort working #92

- src/column/AColumn.ts
- src/column/ColumnManager.ts
- src/styles/_app.scss
- src/styles/_app2.scss
addressed #60, smarter behavior depends on the implementation of #106
> Column locking

- src/SupportView.ts
- src/app2.ts
- src/column/ColumnManager.ts
- src/filter/FilterManager.ts
#108 The current state is shown in the issue section. @mijar @katush  Please check.
> move the primary sort col on first in filter view

- src/app2.ts
- src/column/AColumn.ts
- src/column/AVectorColumn.ts
- src/column/ColumnManager.ts
- src/column/SortColumn.ts
- src/sortColumn/SortColumn.ts
@mijar @katush Could you try to see on your side.
> hierarchical Sorting

- src/filter/CategoricalFilter.ts
@katush @mijar Please check on your side.
> trimmed the name which are longer #123

- src/filter/NumberFilter.ts
@mijar @katush Please check on your side.
> quick fix  #119

- src/SupportView.ts
- src/filter/CategoricalFilter.ts
@mijar @katush Please check on your side.
> TCGA color

- src/column/AColumn.ts
- src/column/ColumnManager.ts
- src/index.ts
- src/styles/_columnManager.scss
@mijar @katush Please check on your side
> dragging column position #53

- src/SortEventHandler/SortEventHandler.ts
- src/column/AVectorColumn.ts
- src/column/ColumnManager.ts
- src/filter/FilterManager.ts
@katush @mijar Please check on your side.
> change order of asc or dsc from column header

- src/SupportView.ts
- src/app.ts
- src/column/MatrixColumn.ts
- src/filter/AFilter.ts
- src/filter/FilterManager.ts
@mijar @katush When the matrix is added new filter view is added for each matrix. #114
> Adding matrix view new 

- tests/demo.test.ts
> removed dummy test file

- src/app.ts
- src/filter/AFilter.ts
- src/filter/AVectorFilter.ts
- src/filter/CategoricalFilter.ts
- src/filter/FilterManager.ts
- src/filter/NumberFilter.ts
- src/filter/StringFilter.ts
- src/styles/_filterManager.scss
> New style for filter area #145

- data/index.json
@mijar @katush  changed color in gender
> updated color for gender #148

- src/filter/CategoricalFilter.ts
- src/styles/_filterManager.scss
@katush @mijar The name of the category should be shown below.
> Put category label under categories #154

- src/filter/NumberFilter.ts
- src/styles/_filterManager.scss
- tests/demo.test.ts
@mijar @katush I have replaced the slider by brushing in numerical filter.Please check if this is properly working or not.
> Brushing test

- src/app.ts
- src/column/AColumn.ts
- src/column/ColumnManager.ts
- src/column/MatrixColumn.ts
@mijar @katush . The problem was due to the undefined range for the column of the matrix, so the order was messed. I have tested another multiple matrices by filter and adding also. Please check before you merge.
> bug fix #158

- src/SupportView.ts
@katush @mijar For now i just updated the order of color to make the consistent color of gender in tcga and artists.
> changed color values

- src/column/AColumn.ts
- src/styles/_columnManager.scss
> corrected header name.

- src/SortEventHandler/SortEventHandler.ts
- src/column/AVectorColumn.ts
- src/column/ColumnManager.ts
- src/filter/AVectorFilter.ts
- src/filter/CategoricalFilter.ts
- src/filter/FilterManager.ts
@katush @mijar Please check on your side.
> Update the category order in filter view by sorting criteria

- src/column/NumberColumn.ts
- src/filter/NumberFilter.ts
- src/styles/_filterManager.scss
@mijar @katush Addressing numerical brushing with window and rendering the values in histogram
> Updating brush #152

- src/filter/CategoricalFilter.ts
The labels sorted was fixed
closed #179
> bug fix #179

- src/filter/CategoricalFilter.ts
- src/styles/_filterManager.scss
> Click on category filter names (#180)

- src/filter/NumberFilter.ts
- src/styles/_filterManager.scss
@mijar @katush @thinkh .
Removed rectangle in the numerical filter but added line and small triangle to indicate as the pointer.
Closed #185
> added line window #185

- src/filter/CategoricalFilter.ts
- src/styles/_filterManager.scss
@mijar @katush @thinkh I have specified the max width for the right panel.
> added span and gave max width for right panel #184

- src/column/StringColumn.ts
@thinkh @katush @mijar 
Referenced from https://github.com/Caleydo/mothertable/issues/93
> switch string from table to list

- src/column/ColumnManager.ts
> bugfix cannot sort if matrix is added at first.

- src/column/ColumnManager.ts
@thinkh When we add matrix at first the scaling in height was broken.
> fix for adding matrix at beginning the scale was broken.

- src/column/AColumn.ts
- src/column/AVectorColumn.ts
- src/column/CategoricalColumn.ts
- src/column/MatrixColumn.ts
- src/column/NumberColumn.ts
- src/column/StringColumn.ts
- src/styles/_taggle-vis.scss
@thinkh @katush  Keep active visualization on multiform update
> keep active vis on multiform update #210

- src/SupportView.ts
- src/column/ColumnManager.ts
- src/filter/FilterManager.ts
Fix for adding matrix starting from country @thinkh @thinkh
> do not check another idtype #190

- src/SupportView.ts
Add id labels in TCGA @thinkh @katush
> ID labels in TCGA

- src/column/AVectorColumn.ts
- src/column/CategoricalColumn.ts
- src/column/ColumnManager.ts
- src/column/MatrixColumn.ts
- src/column/NumberColumn.ts
- src/column/StringColumn.ts
- src/column/VisManager.ts
Magic box basic functionality #212
> Feature #212

- src/column/ColumnManager.ts
> Bugfix for null selection

- src/SupportView.ts
- src/app.ts
- src/column/AColumn.ts
- src/column/AVectorColumn.ts
- src/column/CategoricalColumn.ts
- src/column/ColumnManager.ts
- src/column/MatrixColumn.ts
- src/column/NumberColumn.ts
- src/column/StringColumn.ts
- src/filter/AFilter.ts
- src/filter/AVectorFilter.ts
- src/filter/CategoricalFilter.ts
- src/filter/FilterManager.ts
- src/filter/MatrixFilter.ts
- src/filter/NumberFilter.ts
- src/filter/StringFilter.ts
- src/styles/_filterManager.scss
I removed some old code and switched to D3. 
Please have a look, if everything is still working as before.
> Code refactoring and switch to D3

- src/SortEventHandler/SortEventHandler.ts
- src/SortHandler/SortHandler.ts
- src/column/AColumn.ts
- src/column/CategoricalColumn.ts
- src/column/ColumnManager.ts
- src/column/VisManager.ts
- src/column/utils.ts
- src/filter/AVectorFilter.ts
- src/filter/CategoricalFilter.ts
- src/filter/FilterManager.ts
- src/styles/_filterManager.scss
- src/styles/_taggle-vis.scss
The stratification based on new layout.
> Stratification

- src/SortHandler/SortHandler.ts
> Do not override numerical by categorical #249

- src/column/AColumn.ts
- src/column/AggSwitcherColumn.ts
- src/column/ColumnManager.ts
- src/styles/_columnManager.scss
See #246 
*Todo:*
* Fix height bug
* Replace with buttons
* Switch all groups with button in header
> Aggregation switcher for multiform groups

- src/SupportView.ts
> start with adding stratfications as fake vectors

- src/column/AColumn.ts
should also fix the matrix freezing error
> use the direct vis.list method to get the list available visualizations

- src/column/ColumnManager.ts
- src/column/VisManager.ts
- src/column/utils.ts
- src/filter/FilterManager.ts
I have turned off the stratification icon on categorical filters when it is below numerical or string
> removed the stratification icon on categorical column after numerical

- src/SortHandler/SortHandler.ts
- src/app.ts
- src/column/AColumn.ts
- src/column/AVectorColumn.ts
- src/column/ColumnManager.ts
- src/column/MatrixColumn.ts
- src/column/TaggleMultiform.ts
- src/column/VisManager.ts
- src/column/utils.ts
- src/styles/_columnManager.scss
- src/styles/_taggle-vis.scss
contains corrected brushing as well as fixed aggregation bug related to brushing
Depended PRs
* https://github.com/phovea/phovea_vis/pull/46
* https://github.com/phovea/phovea_core/pull/105
> Brushing fix

- src/column/CategoricalColumn.ts
- src/column/ColumnManager.ts
- src/column/NumberColumn.ts
- src/column/VisManager.ts
- src/styles/_taggle-vis.scss
Includes:
* #265
* Fixes the matrices duplication bug on stratifying a column
> Tweak styling and default heights

- src/column/AggSwitcherColumn.ts
- src/column/ColumnManager.ts
- src/column/VisManager.ts
- src/styles/_columnManager.scss
> Style AggSwitcher icons

- package.json
- src/SupportView.ts
- src/style.scss
- src/styles/_select2.scss
See #266
Note: Please update your dependencies.
1. `yo povea:workspace`
2. `npm install`
> Use select2 for attribute selection (#266)

- src/column/ColumnManager.ts
fix https://github.com/Caleydo/mothertable/issues/280
> Remove brush splitting for aggregated groups

- src/app.ts
- src/column/AColumn.ts
- src/column/AColumnManager.ts
- src/column/AVectorColumn.ts
- src/column/CategoricalColumn.ts
- src/column/ColumnManager.ts
- src/column/MatrixColumn.ts
- src/column/NumberColumn.ts
- src/column/StringColumn.ts
- src/column/VisManager.ts
- src/styles/_columnManager.scss
- src/styles/_filterManager.scss
- src/styles/_taggle-vis.scss
Related PR
https://github.com/phovea/phovea_vis/pull/50
> Add additional attributes on top of matrix

- src/column/AVectorColumn.ts
- src/column/CategoricalColumn.ts
- src/column/NumberColumn.ts
- src/styles/_taggle-vis.scss
See #299 + #301 
Related PR: https://github.com/phovea/phovea_vis/pull/52
> Set histogram y-scale and number of bins per column

- src/column/AggSwitcherColumn.ts
- src/column/ColumnManager.ts
- src/column/MatrixColumn.ts
- src/styles/_columnManager.scss
- src/styles/_taggle-vis.scss
- src/styles/_vars.scss
> Several style fixes for the AggSwitcher column and the column header

- src/column/ColumnManager.ts
Reset sort when the numerical column is at beginning.
> Reset sort when numerical in first #292

- src/SupportView.ts
- src/app.ts
- src/column/AColumn.ts
- src/column/AColumnManager.ts
- src/column/AVectorColumn.ts
- src/column/ColumnManager.ts
- src/column/MatrixColumn.ts
- src/filter/AVectorFilter.ts
- src/filter/CategoricalFilter.ts
- src/filter/FilterManager.ts
I replaced the global sort event by local.
Before if we have two matrices the sort event coming from one matrix was also propagated to whole other matrices which are now fixed.
> Updated Sort Event

- src/column/AggSwitcherColumn.ts
- src/column/ColumnManager.ts
Change default automatic mode to preset user selected unaggregated mode
> Change default automatic mode to preset user selected unaggregated mode

- src/SortHandler/SortHandler.ts
- src/SupportView.ts
- src/app.ts
- src/column/AColumn.ts
- src/column/AColumnManager.ts
- src/column/CategoricalColumn.ts
- src/column/ColumnManager.ts
- src/column/MatrixColumn.ts
- src/column/NumberColumn.ts
- src/column/utils.ts
- src/filter/AVectorFilter.ts
- src/filter/FilterManager.ts
- src/filter/NumberFilter.ts
- src/styles/_columnManager.scss
Related PR : 
https://github.com/phovea/phovea_core/pull/110
> Matrix aggregation first iteration

- src/SupportView.ts
- src/column/ColumnManager.ts
- src/column/utils.ts
Removes the multiform splitting which was introduced for the fisheye effect.
Related to https://github.com/phovea/phovea_vis/pull/56
> Removed fisheye

- src/app.ts
- src/column/AggSwitcherColumn.ts
- src/column/ColumnManager.ts
- src/column/RowNumberColumn.ts
- src/styles/_columnManager.scss
Should solve https://github.com/Caleydo/taggle/issues/342. This column is excluded from all typical row features (sorting, stratification, deletion...) and is only there to show the row numbers.
> Row number column

- phovea.js
- src/column/VisManager.ts
- src/styles/_taggle-vis.scss
- src/vis/LabelVis.ts
Should fix https://github.com/Caleydo/taggle/issues/311
> Stringcolumn aggregation

- src/column/ColumnManager.ts
Issue : https://github.com/Caleydo/taggle/issues/140
> Re calculate sort after column is removed

- src/column/MatrixColumn.ts
See : https://github.com/Caleydo/taggle/issues/332
> Filter data of vector same as matrix column direction

- src/styles/_columnManager.scss
See Issue: https://github.com/Caleydo/taggle/issues/320
> Fix position of reversed attributes on matrix top

- src/SortHandler/SortHandler.ts
- src/SupportView.ts
- src/styles/_taggle-vis.scss
improve filterRangeByName for better performance
fix dataset color setting and detection and try to fix the phovea-vis-list
@thinkh what was the initial intention by using a flex within the list item?
> Dataset fixes

- src/column/AColumn.ts
- src/column/AVectorColumn.ts
- src/column/AggSwitcherColumn.ts
- src/column/CategoricalColumn.ts
- src/column/MatrixColumn.ts
- src/column/NumberColumn.ts
- src/column/RowNumberColumn.ts
- src/column/StringColumn.ts
- src/styles/_columnManager.scss
- src/styles/_taggle-vis.scss
* narrower default width of vector columns
* floating toolbar with buttons in header
* addreses #348
> Narrower column width & floating toolbar

- src/styles/_select2.scss
> address #330 dynamic and reduce selection box size

- src/column/CategoricalColumn.ts
- src/column/MatrixColumn.ts
- src/styles/_taggle-vis.scss
Closes #174
Needs https://github.com/phovea/phovea_vis/pull/62
> Added heatmap_stroke_selection

- src/vis/OneBinHistogram.ts
Fixes https://github.com/Caleydo/taggle/issues/388
When resizing the column, the histogram resizes as well now.
> Update width of OneBinHistogram

- src/MatrixSupportView.ts
- src/SupportView.ts
- src/app.ts
- src/column/AColumnManager.ts
- src/column/ColumnManager.ts
- src/column/MatrixColumn.ts
- src/filter/DensityPlot.ts
- src/filter/FilterManager.ts
Closes https://github.com/Caleydo/taggle/issues/306
> Remove columns from the top of matrix 

- src/SupportView.ts
- src/app.ts
- src/column/AColumn.ts
- src/column/ColumnManager.ts
- src/filter/AFilter.ts
- src/filter/AVectorFilter.ts
- src/filter/FilterManager.ts
- src/filter/MatrixFilter.ts
- src/styles/_columnManager.scss
- src/styles/_filterManager.scss
- src/styles/_vars.scss
closes https://github.com/Caleydo/taggle/issues/362 and https://github.com/Caleydo/taggle/issues/217
> Visually link column and support view header

- src/column/ColumnManager.ts
- src/filter/FilterManager.ts
> Bug fix for issue #412

- src/column/ColumnManager.ts
- src/column/NumberColumn.ts
> Fix typo and aggregation button consistency 

- src/MatrixSupportView.ts
- src/SupportView.ts
- src/app.ts
- src/column/AColumnManager.ts
- src/column/MatrixColumn.ts
Closes https://github.com/Caleydo/taggle/issues/352
> Set first categorical column as stratification
